### PR TITLE
bug in installing the http support in php

### PR DESCRIPTION
**Pull request by akash3456**
I seem to be getting an issue on my pecl installation of http support and it seems to have installed a stable version of the pecl package but it does not appear in my phpinfo and i get the following messages in the terminal shell: 

Unable to load dynamic library '/usr/lib/php5/20131226/http.so' - /usr/lib/php5/20131226/http.so: undefined symbol: php_resource_factory_handle_ctor in Unknown on line 0

### CODE REVIEW

**Comment by m6w6** [comment]
Looks like you've accidentally opened a pull request. Anyway, pleas upgrade the raphf PECL module.

**Comment by m6w6** [comment]
Also https://github.com/m6w6/ext-http is the new location for this extension.

**Comment by akash3456** [comment]
the raphf mode is the latest version

**Comment by akash3456** [comment]
i get this message now : call to undefined function http_build_url () function in php

**Pull request closed without merging**
